### ISSUE TITLE
请求添加toc和搜索功能

### ISSUE THREAD

**Issue by Pathsis** [Lonor/site#134]
您好，非常喜欢您的模板，有个不情之请，可否增加文章目录和搜索功能呢？

**Comment by Lonor** [comment]
近期会实现搜索功能。
关于 ToC，由于博客内容不像专业文档，内容上不强调章节关系，所以优先级不高。如果实现起来容易的话我也会加上。

很高兴你喜欢这套设计。
/label feature
/label todo

**Comment by Pathsis** [comment]
非常期待。

**Comment by Lonor** [comment]
/re-open

@Pathsis  关于 ToC 后续我会尝试实现看看。基于 Remark/Rehype 生态：
https://github.com/remarkjs/remark-toc or https://github.com/JS-DevTools/rehype-toc

**Comment by Pathsis** [comment]
太厉害了，效果特别好！万分感谢！☺️
