### ISSUE TITLE
页面路由、404页面和亮/暗主题切换

### ISSUE THREAD

**Issue by Pathsis** [Lonor/site#137]
hi，Lonor！

我又来打扰您了。有几个问题想求助于您：

1. 打算把博客迁移到这个模版上，但以前的帖子链接地址格式是`domain.com/post-title/`，这个模板有办法使现有的帖子链接地址格式`domain.com/blog/post-title`变成上面这个格式吗？
2. 可否将主页地址`/`映射到`/about`?
3. 这个模板似乎没有恰当的404页面，没有回到首页的链接。
4. 有打算支持亮暗主题切换吗？发现了一个挺优雅的主题切换实例：https://github.com/alexcarpenter/alexcarpenter-next ，以及这个：https://github.com/alexcarpenter/nextjs-mdx-blog-theme

我是个编程小白，其他的静态网站生成器还能手动改下模版什么的，nextjs真的束手无策，看了官方文档尝试改了好久也没有成功，所以才为这些“小事”叨扰您。如果打扰到您了，敬请见谅并忽略。

再次感谢！

**Comment by Lonor** [comment]
1. 目前仅支持把中间 `**/blog/**` 换成其他类似 `**/xxx/**` 这种路径， 你的这种方式可以考虑用 middleware 做 301 跳转
2. 可以，只要把 `pages` 路径下面的 `about.js` 重命名成 `index.js`, 原有的 `index.js` 再换成比如 `blog.js`
3. 404 可以自定义，我没用做，个人不太需要；回首页的地方我刻意做了隐藏，文章页可以点击作者的位置跳转首页
4. 默认已经支持了操作系统的 Dark Mode 自动更换

其实我个人也是基于 next.js 官网教程一步一步搭建此项目的。你也可以参考学习：https://nextjs.org/learn/basics/create-nextjs-app
只要 React 基础和 JavaScript 熟练使用，写出类似的项目不会很困难。
另外 Vercel 提供了很多类似的博客模板：https://vercel.com/templates?search=blog 很多也是直接基于 markdown 做 SSG 的。我的这个项目来来回回改了大半年了，有很多琐碎细节，反而不太利于你做修改。

/label question

**Comment by Pathsis** [comment]
非常感谢您的回复！

不知道怎么利用middleware 做 301 跳转？

补充下第2点，默认的404页面没有回到首页的链接（没有任何链接），而不是帖子页没有回首页链接。

**Comment by Lonor** [comment]
在 middleware.js 文件中，可以写一个中间件函数，用于检查是否需要进行重定向。

```javascript
export default function(req, res, next) {
  if (req.url === '/old-page') {
    res.redirect(301, '/blog/new-page');
  } else {
    next();
  }
}
```

在 pages 目录下创建一个 old-page.js 文件，作为需要重定向的旧页面。

访问 http://localhost:3000/old-page，应该会自动重定向到 http://localhost:3000/new-page。
需要注意的是，如果需要进行多个重定向，可以在 _middleware.js 文件中添加多个中间件函数，按照顺序进行检查和重定向。同时，需要确保在重定向之前调用 next() 函数，否则可能会出现错误。


404 自定义配置其实非常简单 (#142)。很多内容其实是因为不久前刚发布的 Next.js 13 最新版本会基于 `app` 文件夹做重新设计，所以现在在 `pages` 文件夹下做变动就显得有点过时了，所以才没管这些。

**Comment by Pathsis** [comment]
万分感谢！

**Comment by Pathsis** [comment]
页面路由的问题，我的理解是，**为以前所有的旧帖子在pages文件下分别建立old-pages.js，然后在middleware中逐个建立路由，然后新的帖子今后默认domain.com/blog/post-title的地址格式**，是这样吗？

如果是的，那么我原先用markdown写的文章咋变成js文件呢？😴

**Comment by Lonor** [comment]
> 页面路由的问题，我的理解是，**为以前所有的旧帖子在pages文件下分别建立old-pages.js，然后在middleware中逐个建立路由，然后新的帖子今后默认domain.com/blog/post-title的地址格式**，是这样吗？
> 
> 
> 
> 如果是的，那么我原先用markdown写的文章咋变成js文件呢？😴
> 
> 

应该不是一定非要把原始 old.page.js 建立，只要在 middleware 中定义好路由规则，理论上就可以了，就像短链接跳转一样。
原先的文章放在 blog 路径下就行，markdown 会在 build 阶段生成对应的静态资源。

**Comment by Pathsis** [comment]
> > 页面路由的问题，我的理解是，**为以前所有的旧帖子在pages文件下分别建立old-pages.js，然后在middleware中逐个建立路由，然后新的帖子今后默认domain.com/blog/post-title的地址格式**，是这样吗？
> > 如果是的，那么我原先用markdown写的文章咋变成js文件呢？😴
> 
> 应该不是一定非要把原始 old.page.js 建立，只要在 middleware 中定义好路由规则，理论上就可以了，就像短链接跳转一样。 原先的文章放在 blog 路径下就行，markdown 会在 build 阶段生成对应的静态资源。

多谢指点。虽然对js一窍不通的我一筹莫展😄

**Comment by Pathsis** [comment]
试了下，在next.config.js文件中写入如下代码，可以实现跳转：

```js
async redirects() {
    return [
      {
        source: "/post-title",
        destination: "/blog/post-title",
        permanent: true,
      },
    ];
  },
```

不过有个问题，是不是必须得逐个建立跳转链接？

还有，在nextjs必须是domain.com/blog/post-title格式而不能domain.com/post-title格式的地址吗？

**Comment by Pathsis** [comment]
改成这个
```js
{
        source: "/${post.id}",
        destination: "/blog/${post.id}",
        permanent: true,
      },
```
就不需要逐个设置了。于是只剩下**是否可以用domain.com/post-title格式的地址**的问题了。

**Comment by Pathsis** [comment]
> 改成这个
> 
> ```js
> {
>         source: "/${post.id}",
>         destination: "/blog/${post.id}",
>         permanent: true,
>       },
> ```
> 
> 就不需要逐个设置了。于是只剩下**是否可以用domain.com/post-title格式的地址**的问题了。

这样不行，运行`npm run dev`出现如下错误提示：

```shell
 npm run build

> blog@1.0.0 build
> next build && pnpm feed && next-sitemap

`destination` has segments not in `source` or `has` () for route {"source":"/${post.id}","destination":"/blog/${post.id}","permanent":true}


Error: Invalid redirect found
```

**Comment by Lonor** [comment]
我还是建议逐个跳转，否则 `/about` 会跳转到 `/blog/about`.

**Comment by Pathsis** [comment]
> 我还是建议逐个跳转，否则 `/about` 会跳转到 `/blog/about`.

太感谢了！打算这样做了！

另外，搜索还有一个小问题：点击某个搜索结果，返回页面后，搜索结果不能保留，这挺影响使用体验的，要是您有空的话，或许可以优化下☺️

**Comment by Pathsis** [comment]
> ```js
> /${post.id}
> ```

我发现添加：
```js
{
        source: "/[id]",
        destination: "/blog/[id]",
        permanent: true,
      },
```
可以实现正常跳转。
