### ISSUE TITLE
搜索不支持分词

### ISSUE THREAD

**Issue by Pathsis** [Lonor/site#147]
Hi Lonor，我又来打扰你啦！

想报告一个问题，搜索不支持分词。

仅仅是提出改进的希望……☺️

**Comment by Pathsis** [comment]
好像有人用盘古分词来解决这个问题。另外，最近出了个专门用于nextjs的flexsearch。

**Comment by Lonor** [comment]
> 只能考虑使用第三方 saas。目前成熟的方案有 Algolia。

Good suggestion! 我有空了解一下。https://github.com/nextapps-de/flexsearch

**Comment by Lonor** [comment]
> 好像有人用盘古分词来解决这个问题。另外，最近出了个专门用于nextjs的flexsearch。

Good suggestion! 我有空了解一下。https://github.com/nextapps-de/flexsearch

**Comment by Pathsis** [comment]
vercel员工Shu Ding开发的nextjs框架的静态博客生成器nextra好像就默认采用flexsearch。
