### ISSUE TITLE
目前搜索功能的三个问题

### ISSUE THREAD

**Issue by Pathsis** [Lonor/site#150]
新的搜索引擎速度太快了！👍🏻

目前有三个问题：

1.搜索结果中页面标题比其中的一级标题显示更大；
<img width="820" alt="截屏2023-03-17 17 09 08" src="https://user-images.githubusercontent.com/72077265/225861952-91ac1b6e-0b23-4654-98cd-b9ac4563475b.png">
2. 搜索结果不易于区分两个帖子；
3.点击搜索结果后返回，搜索结果会消失。

**Comment by Pathsis** [comment]
标题大小问题应该出在search.js中将帖子的标题设置成了h3.

```js
 <h3
                  dangerouslySetInnerHTML={{
                    __html: `${searchResult.title.replace(
                      keywords,
                      `<mark>${keywords}</mark>`,
                      "gi"
                    )}`,
                  }}
                />
              ) : (
                <h3>{searchResult.title}</h3>
```
改成`h1`就好啦。

---

**补充一个问题**，当搜索tags关键词时，会返回图片，但结果不能显示：

例如，搜搜`Robot`：

<img width="392" alt="截屏2023-03-17 18 17 01" src="https://user-images.githubusercontent.com/72077265/225877745-8c943839-7ddc-4359-b460-5be240b6c566.png">

当在该图片附近搜`MongoDB`，不会返回图片，正常：

<img width="381" alt="截屏2023-03-17 18 22 35" src="https://user-images.githubusercontent.com/72077265/225878465-27528275-923d-414b-ac5b-3a710d29ab48.png">

**Comment by Pathsis** [comment]
搜索时，返回很多关于图片的404错误：


https://user-images.githubusercontent.com/72077265/225899614-a8dd8f03-3758-470b-aa63-9122ec921beb.mp4

**Comment by Lonor** [comment]
/label bug

现在的搜索使用 FlexSearch 将文章 json 全部缓存到浏览器内中，所以理论上断网了也能做搜索，也是快的原因。

图片的问题是图片的链接刚好包含了搜索关键词，而我做了全局高亮把链接内的内容也被替换掉，这导致了 404.

我周末再看看改改。感谢指出问题。

**Comment by Lonor** [comment]
> 此外，后退清空搜索结果的问题是不是没有办法解决呢？

我一直没理解这句话的意思。
我这里的做法是输入框只需要输入文字，不需要回车或确认操作就直接展示当前搜索结果，你这里的`后退`是指在搜索栏逐字删除吗？

**Comment by Pathsis** [comment]
> > 此外，后退清空搜索结果的问题是不是没有办法解决呢？
> 
> 我一直没理解这句话的意思。 我这里的做法是输入框只需要输入文字，不需要回车或确认操作就直接展示当前搜索结果，你这里的`后退`是指在搜索栏逐字删除吗？

我这里讲的简略了。上次说的比较详细。

1. 搜索一个关键词；
2. 点击一个返回结果；
3. 浏览器后退；
4. 搜索结果清空。

我有些怀疑这是nextjs特别令人讨厌的老毛病。

**Comment by Lonor** [comment]
后退时结果清空和 Next.js / React 没关系。搜索的内容需要保留在页面当前的 URL 参数之中。

**Comment by Pathsis** [comment]
> 后退时结果清空和 Next.js / React 没关系。搜索的内容需要保留在页面当前的 URL 参数之中。

"搜索的内容需要保留在页面当前的 URL 参数之中"，这个不知道是什么意思？

**Comment by Lonor** [comment]
就是要把查询的字符串同步到页面链接上。目前是在 React Component 页面 State 中（可以理解为浏览器内存）。
最终呈现的效果：

1. 搜索查询 `abc` -> 页面 URL 在执行搜索后自动变成 `example.com/search?query=abc`
2. 直接访问 `example.com/search?query=xyz` -> 页面直接呈现搜索 `abc` 的结果

Next.js 实现这类功能可能需要 SSR（服务端渲染），但这不是比较友好的实现方式。我还是想把这个功能尽量放在浏览器端做。

**Comment by Pathsis** [comment]
是的，这是ChatGPT给我创建的一个时间戳组件：

```js
// ./components/Timestamp.js

import { useEffect, useState } from "react";

const Timestamp = () => {
  const [projectCreationTime, setProjectCreationTime] = useState(new Date());
  const [projectInfoLoaded, setProjectInfoLoaded] = useState(false);

  useEffect(() => {
    const getProjectInfo = async () => {
      try {
        // 如果已经获取了项目信息，则不再发送 API 请求
        if (projectInfoLoaded) {
          return;
        }

        // 获取 Vercel 部署列表
        const response = await fetch(
          `https://api.vercel.com/v6/now/deployments?projectId=prj_VWf0ZGwTtFTEU58ALqsGLnK1shq2&limit=1`,
          {
            headers: {
              Authorization: `<省略>`,
            },
          }
        );

        // 解析响应 JSON 格式数据
        const data = await response.json();

        // 设置项目创建时间为响应中的部署日期
        setProjectCreationTime(data.deployments[0].created);
        setProjectInfoLoaded(true);
      } catch (error) {
        console.error(error);
      }
    };

    getProjectInfo();
  }, [projectInfoLoaded]);

  return (
    <div className="text-gray-400">
      {" "}
      {new Date(projectCreationTime).toLocaleString("en-US")}
    </div>
  );
};

export default Timestamp;
```
每次点击页面都会fetch大约1.3kb的数据，消耗约350毫秒。

我有个疑问，现在你的这个github commit信息，是否SSG建构阶段生成的吗？

**Comment by Lonor** [comment]
时间戳是在构建阶段获取到的。
Vercel 其实内置了这个 commit hash 的环境变量：
https://vercel.com/docs/concepts/projects/environment-variables/system-environment-variables#framework-environment-variables

**Comment by Pathsis** [comment]
马上换你这个。不好意思，我上一条信息发错了issue。

**Comment by Pathsis** [comment]
> 就是要把查询的字符串同步到页面链接上。目前是在 React Component 页面 State 中（可以理解为浏览器内存）。 最终呈现的效果：
> 
> 1. 搜索查询 `abc` -> 页面 URL 在执行搜索后自动变成 `example.com/search?query=abc`
> 2. 直接访问 `example.com/search?query=xyz` -> 页面直接呈现搜索 `abc` 的结果
> 
> Next.js 实现这类功能可能需要 SSR（服务端渲染），但这不是比较友好的实现方式。我还是想把这个功能尽量放在浏览器端做。

懂了，确实如此。如果可以SSR，也挺好的啊，毕竟search页面不常打开。

**Comment by Pathsis** [comment]
> 就是要把查询的字符串同步到页面链接上。目前是在 React Component 页面 State 中（可以理解为浏览器内存）。 最终呈现的效果：
> 
> 1. 搜索查询 `abc` -> 页面 URL 在执行搜索后自动变成 `example.com/search?query=abc`
> 2. 直接访问 `example.com/search?query=xyz` -> 页面直接呈现搜索 `abc` 的结果
> 
> Next.js 实现这类功能可能需要 SSR（服务端渲染），但这不是比较友好的实现方式。我还是想把这个功能尽量放在浏览器端做。

目前我采取的措施是，在新的标签页打开搜索结果，应该说解决了返回清空搜索结果的问题。
