### ISSUE TITLE
是否可添加网站建构信息？

### ISSUE THREAD

**Issue by Pathsis** [Lonor/site#153]
有一个想法，在页脚显示建构信息，主要是最后建构时间：

1. 第一个想法是，nextjs是否有类似于jekyll的{site.time}？
2. 如果没有，是否可以拉取GitHub的commit信息。一个参考是：https://www.aleksandrhovhannisyan.com/blog/eleventy-build-info/
3. 或者，拉取Vercel的部署信息，一个参考是：https://github.com/orgs/vercel/discussions/587#discussioncomment-2670125 如果能够拉取Vercel的Ready或Error信息就好酷啊，并且在页脚显示一个绿色或红色的状态指示灯以及“created date”。

<img width="168" alt="截屏2023-03-20 22 39 43" src="https://user-images.githubusercontent.com/72077265/226374034-a8e8f55a-75be-4cd3-82e8-d395cb2f4c9f.png">

**Comment by Pathsis** [comment]
这个太厉害了！我自己让ChatGPT教我，勉强弄了个，但每次点击页面都得读取[Vercel REST API](https://vercel.com/docs/rest-api)，怕有速率限制。

**Comment by Lonor** [comment]
本地 dev 环境可以在 `package.json` 里尝试用 `git rev-parse HEAD` 获取到 git commit hash 字符串，从而让页面获取到：

```
"dev": "pnpm feed && NEXT_PUBLIC_BUILDTIME=$(date '+%s') NEXT_PUBLIC_VERCEL_GIT_COMMIT_SHA=$(git rev-parse HEAD) next dev -H 0.0.0.0"
```

https://github.com/Lonor/site/blob/68b2746c205cd8ecb10bd71cf2f885c119d422c7/components/footer.js#L8-L9

**Comment by Pathsis** [comment]
太厉害了！你这个可以发布主题了，真的是目前nextjs框架下的主题的一股清流！

另外，弱弱地问，ToC还有计划吗？找了好多资料，自己试了好多次，都不行，不会js（😞）。有一个目录显示在文章前，对于读者预览文章的概要还是挺重要的。
