### ISSUE TITLE
可能的性能问题

### ISSUE THREAD

**Issue by Pathsis** [Lonor/site#155]
当我尝试将85篇文章迁移至此，lighthouse的性能评分从98下降到64.

<img width="471" alt="截屏2023-03-21 12 42 28" src="https://user-images.githubusercontent.com/72077265/226518714-2d975320-b226-4f47-a3ed-51301a842b3a.png">

npm run dev的提示如下：

```shelll
Warning: data for page "/blog" is 1.54 MB which exceeds the threshold of 128 kB, this amount of data can reduce performance.
```

我不确定这是不是真正的性能问题。

**Comment by Lonor** [comment]
Blog index 页在 SSG 时将 markdown 全文细节都带入进页面。只需要将包含此全文的字段移除。

/label enhancement

**Comment by Lonor** [comment]
https://github.com/Lonor/site/pull/157/commits/7f44f0285ab5b0ae3a1e1ee74860c167f9b978b9

**Comment by Pathsis** [comment]
在网站上的新的性能评分报告（移动设备下）：

<img width="460" alt="截屏2023-03-21 19 19 50" src="https://user-images.githubusercontent.com/72077265/226591079-c1cf6e58-11c9-42ce-ac6d-020c5669e3f0.png">

应该是没问题了，棒极了！❤
