### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by Lonor** [Lonor/site#167]
Add a new page (link in footer) to tell our reader about the privacy policy.

**Comment by Pathsis** [comment]
缺少对第三方隐私数据收集的说明，比如豆瓣和B站，其收集的数据似乎特别多，而且不受主站管理😊

**Comment by Lonor** [comment]
> 缺少对第三方隐私数据收集的说明，比如豆瓣和B站，其收集的数据似乎特别多，而且不受主站管理😊

全让 GPT 给我写好了，哈哈

**Comment by Pathsis** [comment]
> > 缺少对第三方隐私数据收集的说明，比如豆瓣和B站，其收集的数据似乎特别多，而且不受主站管理😊
> 
> 全让 GPT 给我写好了，哈哈

哈哈😄
