### ISSUE TITLE
和Mastodon可以互通吗?

### ISSUE THREAD

**Issue by springrain** [Lonor/site#188]
发布的内容可以自动同步到Mastodon吗? 如果是和Mastodon是双向同步,就最好不过了

**Comment by Lonor** [comment]
文章会自动以 Outbox 形式发布。这个项目里没有完全实现 ActivityPub 协议规定的所有 Endpoint，所以无法同步，仅作展示用途。

**Comment by springrain** [comment]
> 文章会自动以 Outbox 形式发布。这个项目里没有完全实现 ActivityPub 协议规定的所有 Endpoint，所以无法同步，仅作展示用途。

我在 [mastodon.social](https://mastodon.social/@lawrence@lawrenceli.me) 看到了你的账号,里面的信息和你的outbox是一致的,这个是单项同步到了mastodon吗?

**Comment by Lonor** [comment]
> 我在 https://mastodon.social/@lawrence@lawrenceli.me 看到了你的账号,里面的信息和你的outbox是一致的,这个是单项同步到了mastodon吗?

不能算作同步，只是实现了 Outbox 接口之后，就会被任一 Mastodon 实例搜索到，是被动的过程 —— 即用户在某个实例上搜索的时候，该实例才回去获取我的 Outbox JSON。

**Comment by springrain** [comment]
好的,非常感谢,您的这个项目计划和mastodon互通吗?如果可以的话,方便加个好友吗?

**Comment by Lonor** [comment]
> 好的,非常感谢,您的这个项目计划和mastodon互通吗?如果可以的话,方便加个好友吗?

不打算互通，这个只是我的博客，如果完全互通就相当于一个 Mastodon 实例了，后端承载不了这么庞大的资源；目前仅作一些基础的展示而已。我联系方式发你邮箱了。

/close
/label question
