### ISSUE TITLE
Adding Scroll to top button 

### ISSUE THREAD

**Issue by Ayusht777** [Lonor/site#283]
hi i want to contribute on this project by adding scroll to top button

**Comment by Lonor** [comment]
feel free to raise a pull request :)

**Comment by Ayusht777** [comment]
ok assigned it me under hackoctberfest

**Comment by Ayusht777** [comment]
hey can you provide commands to run this project locally

**Comment by Lonor** [comment]
```sh
cp .env.example .env # may need to set some values in this file
pnpm install
pnpm dev
```

**Comment by Ayusht777** [comment]
can you tell me what values should i add in .env file

**Comment by Ayusht777** [comment]
and did you thought it from pnpm to vite

**Comment by Lonor** [comment]
I am afraid that the env value requires yourself deep diving into the code. 

Currently the package management is pnpm. My next plan is to move it to bun rather than vite. Sorry for that.
